runtime: python27
service: default

api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(gif|png|jpg|less|json|woff|woff2|ttf|eot|scss|css|js|ico|svg)(|\.map))$
    static_files: dist/openfabric/\1
    upload: dist/openfabric/(.*)(|\.map)
  - url: /(.*)
    static_files: dist/openfabric/index.html
    upload: dist/openfabric/index.html
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
